// <auto-generated />
using ITStepRazorApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITStepRazorApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240413130532_SeedingDataBase")]
    partial class SeedingDataBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ITStepRazorApp.Data.Model.PizzaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Chicken")
                        .HasColumnType("bit");

                    b.Property<bool>("ExtraCheese")
                        .HasColumnType("bit");

                    b.Property<bool>("ExtraSauce")
                        .HasColumnType("bit");

                    b.Property<bool>("Ham")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLarge")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSmall")
                        .HasColumnType("bit");

                    b.Property<bool>("Mushroom")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Pepperoni")
                        .HasColumnType("bit");

                    b.Property<bool>("Pineapple")
                        .HasColumnType("bit");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("PizzaModel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Chicken = false,
                            ExtraCheese = false,
                            ExtraSauce = true,
                            Ham = false,
                            IsLarge = true,
                            IsSmall = false,
                            Mushroom = false,
                            Name = "Yuro Deluxe",
                            Pepperoni = true,
                            Pineapple = false,
                            Price = 25f
                        },
                        new
                        {
                            Id = 2,
                            Chicken = false,
                            ExtraCheese = true,
                            ExtraSauce = false,
                            Ham = false,
                            IsLarge = false,
                            IsSmall = true,
                            Mushroom = false,
                            Name = "Yuro Supreme",
                            Pepperoni = false,
                            Pineapple = true,
                            Price = 30f
                        },
                        new
                        {
                            Id = 3,
                            Chicken = true,
                            ExtraCheese = false,
                            ExtraSauce = true,
                            Ham = false,
                            IsLarge = true,
                            IsSmall = false,
                            Mushroom = true,
                            Name = "Yuro Deluxe",
                            Pepperoni = false,
                            Pineapple = false,
                            Price = 25f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
